# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_snap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: samuelmeuli/action-snapcraft@v1.1.3
        with:
          use_lxd: true
      - run: sg lxd -c 'snapcraft --use-lxd'
      - uses: actions/upload-artifact@master
        with:
          name: snap-build
          path: flutter-actions-test_0.1.0_amd64.snap
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: sudo apt install libgtk-3-dev libglib2.0-dev libblkid-dev liblzma-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux
      - run: (cd build/linux/release && tar cfJv linux_build.tar.xz bundle)
      - uses: actions/upload-artifact@master
        with:
          name: linux-build
          path: build/linux/release/linux_build.tar.xz
  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web
      - uses: actions/upload-artifact@master
        with:
          name: web-build
          path: build/web
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - run: flutter build appbundle
      - run: ls -AlR build
      - uses: actions/upload-artifact@master
        with:
          name: android-build
          path: build/app/outputs/bundle/release
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows
      - run: Tree /F build
      - uses: actions/upload-artifact@master
        with:
          name: windows-build
          path: build/windows/release/bundle
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: ls -AlR build
      - uses: actions/upload-artifact@master
        with:
          name: ios-build
          path: build/ios/outputs/bundle/release
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter build macos
      - run: (cd build/macos/Build/Products/Release && tar cfJv macos_build.tar.xz flutter_actions_test.app)
      - run: ls -AlR build
      - uses: actions/upload-artifact@master
        with:
          name: macos-build
          path: build/macos/Build/Products/Release/macos_build.tar.xz
  deploy:
    needs: [build_snap, build_linux, build_web, build_android, build_windows, build_macos]
    runs-on: ubuntu-latest
    steps:
      - run: mkdir public
      - uses: actions/download-artifact@v2
        with:
          path: public
      - run: touch public/index.html
      - run: |
          cat > public/index.html <<EOL
          <!doctype html>
          <html>
          <head>
          <meta encoding="utf-8"/>
          <title>flutter action test builds</title>
          </head>
          <body>
          <div>
          <h3>Latest Builds (${{ github.sha }})</h3>
          <ul>
          <li><a href="snap-build/flutter-actions-test_0.1.0_amd64.snap">snap</a></li>
          <li><a href="linux-build/linux_build.tar.xz">linux</a></li>
          <li><a href="web-build">web</a></li>
          <li><a href="android-build/android_build.tar.xz">android</a></li>
          <li><a href="windows-build/windows_build.zip">windows</a></li>
          <li><a href="#">ios</a></li>
          <li><a href="macos-build/macos_build.tar.xz">macos</a></li>
          </ul>
          </div>
          </body>
          </html>
          EOL
      - run: ls -AlR public
      - uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
